import type {
  AdminOrderRow,
  AdminUser,
  AnalyticsPoint,
  Category,
  Coupon,
  Order,
  Product,
  Review,
  User,
} from '@/types';

export const CATEGORIES: Category[] = [
  { id: 'cat-milk-tea', name: 'Милк-ти', slug: 'milk-tea', emoji: '🧋', color: 'pink' },
  { id: 'cat-fruit-tea', name: 'Фруктовый чай', slug: 'fruit-tea', emoji: '🍓', color: 'mint' },
  { id: 'cat-coffee', name: 'Кофе', slug: 'coffee', emoji: '☕️', color: 'caramel' },
  { id: 'cat-matcha', name: 'Матча', slug: 'matcha', emoji: '🍵', color: 'mint' },
  { id: 'cat-cheese-tea', name: 'Сырный чай', slug: 'cheese-tea', emoji: '🧀', color: 'pink' },
  { id: 'cat-seasonal', name: 'Сезонное', slug: 'seasonal', emoji: '🌸', color: 'caramel' },
];

const img = (id: string) => `https://images.unsplash.com/${id}?q=80&w=1000&auto=format&fit=crop`;

export const PRODUCTS: Product[] = [
  {
    id: 'p-classic-milk-tea',
    name: 'Классический милк-ти',
    slug: 'classic-milk-tea',
    categoryId: 'cat-milk-tea',
    price: 320,
    images: [img('photo-1558857563-b371033873b8'), img('photo-1571934811356-5cc061b6821f')],
    description:
      'Чёрный чай, сваренный на цельном молоке, с мягкой карамельной нотой и классической тапиокой. Тот самый вкус, с которого всё начиналось.',
    tags: ['bestseller'],
    rating: 4.8,
    reviewsCount: 214,
    calories: 210,
    caffeine: 'среднее',
    availableSizes: ['S', 'M', 'L'],
    availableToppings: ['boba-classic', 'boba-brown', 'pudding', 'jelly'],
  },
  {
    id: 'p-brown-sugar-boba',
    name: 'Браун-шугар боба',
    slug: 'brown-sugar-boba',
    categoryId: 'cat-milk-tea',
    price: 360,
    oldPrice: 420,
    images: [img('photo-1546039907-7fa05f864c02'), img('photo-1572442388796-11668a67e53d')],
    description:
      'Тапиока, томлёная в тростниковой карамели, фирменные «тигровые» полосы на стенках стакана и свежее молоко.',
    tags: ['sale', 'signature'],
    rating: 4.9,
    reviewsCount: 341,
    calories: 260,
    caffeine: 'низкое',
    availableSizes: ['S', 'M', 'L'],
    availableToppings: ['boba-brown', 'boba-classic', 'cheese-foam'],
  },
  {
    id: 'p-taro-milk-tea',
    name: 'Таро милк-ти',
    slug: 'taro-milk-tea',
    categoryId: 'cat-milk-tea',
    price: 350,
    images: [img('photo-1497515114629-f71d768fd07c')],
    description: 'Нежное пюре таро, сливочная пенка и лиловый цвет, в который невозможно не влюбиться.',
    tags: ['new'],
    rating: 4.7,
    reviewsCount: 98,
    calories: 240,
    caffeine: 'нет',
    availableSizes: ['S', 'M', 'L'],
    availableToppings: ['boba-classic', 'pudding', 'jelly'],
  },
  {
    id: 'p-strawberry-fruit-tea',
    name: 'Клубничный фруктовый чай',
    slug: 'strawberry-fruit-tea',
    categoryId: 'cat-fruit-tea',
    price: 340,
    images: [img('photo-1558303420-9ba816e5ce76')],
    description: 'Зелёный чай холодного заваривания, свежая клубника и попинг-боба с соком внутри.',
    tags: ['bestseller', 'new'],
    rating: 4.9,
    reviewsCount: 176,
    calories: 180,
    caffeine: 'низкое',
    availableSizes: ['S', 'M', 'L'],
    availableToppings: ['popping-strawberry', 'aloe', 'jelly'],
  },
  {
    id: 'p-mango-passion',
    name: 'Манго-маракуйя купитель',
    slug: 'mango-passion-cooler',
    categoryId: 'cat-fruit-tea',
    price: 350,
    images: [img('photo-1546173159-315724a31696')],
    description: 'Тропический дуэт манго и маракуйи на улуне с кубиками алоэ вера.',
    tags: ['new'],
    rating: 4.6,
    reviewsCount: 61,
    calories: 170,
    caffeine: 'низкое',
    availableSizes: ['S', 'M', 'L'],
    availableToppings: ['popping-mango', 'aloe'],
  },
  {
    id: 'p-flat-white',
    name: 'Флэт уайт',
    slug: 'flat-white',
    categoryId: 'cat-coffee',
    price: 280,
    images: [img('photo-1541167760496-1628856ab772')],
    description: 'Двойной эспрессо и бархатное молоко, взбитое до плотной микропены.',
    tags: ['bestseller'],
    rating: 4.8,
    reviewsCount: 289,
    calories: 140,
    caffeine: 'высокое',
    availableSizes: ['S', 'M'],
    availableToppings: [],
  },
  {
    id: 'p-caramel-latte',
    name: 'Карамельный латте',
    slug: 'caramel-latte',
    categoryId: 'cat-coffee',
    price: 300,
    images: [img('photo-1461023058943-07fcbe16d735')],
    description: 'Эспрессо, молоко и авторский карамельный сироп с нотами топлёных сливок.',
    tags: [],
    rating: 4.7,
    reviewsCount: 152,
    calories: 220,
    caffeine: 'среднее',
    availableSizes: ['S', 'M', 'L'],
    availableToppings: ['cheese-foam'],
  },
  {
    id: 'p-matcha-latte',
    name: 'Матча латте',
    slug: 'matcha-latte',
    categoryId: 'cat-matcha',
    price: 340,
    images: [img('photo-1515823064-d6e0c04616a7')],
    description: 'Церемониальная матча, взбитая венчиком часен, с мягким сливочным молоком.',
    tags: ['signature'],
    rating: 4.9,
    reviewsCount: 203,
    calories: 190,
    caffeine: 'среднее',
    availableSizes: ['S', 'M', 'L'],
    availableToppings: ['jelly', 'pudding'],
  },
  {
    id: 'p-matcha-cheese',
    name: 'Матча с сырной пенкой',
    slug: 'matcha-cheese-foam',
    categoryId: 'cat-matcha',
    price: 370,
    images: [img('photo-1536256263959-770b48d82b0a')],
    description: 'Плотная матча на льду под шапкой солёно-сладкой сырной пенки.',
    tags: ['bestseller'],
    rating: 4.8,
    reviewsCount: 134,
    calories: 250,
    caffeine: 'среднее',
    availableSizes: ['M', 'L'],
    availableToppings: ['cheese-foam'],
  },
  {
    id: 'p-jasmine-cheese-tea',
    name: 'Жасминовый чай с сырной пенкой',
    slug: 'jasmine-cheese-tea',
    categoryId: 'cat-cheese-tea',
    price: 330,
    images: [img('photo-1556679343-c7306c1976bc')],
    description: 'Ароматный жасминовый чай, увенчанный воздушной сырно-сливочной пенкой.',
    tags: [],
    rating: 4.6,
    reviewsCount: 87,
    calories: 200,
    caffeine: 'низкое',
    availableSizes: ['S', 'M', 'L'],
    availableToppings: ['cheese-foam', 'jelly'],
  },
  {
    id: 'p-oolong-cheese-tea',
    name: 'Улун с сырной пенкой',
    slug: 'oolong-cheese-tea',
    categoryId: 'cat-cheese-tea',
    price: 330,
    images: [img('photo-1517701604599-bb29b565090c')],
    description: 'Молочный улун с плотной пенкой из сливочного сыра — баланс солёного и сладкого.',
    tags: ['new'],
    rating: 4.7,
    reviewsCount: 54,
    calories: 210,
    caffeine: 'среднее',
    availableSizes: ['S', 'M', 'L'],
    availableToppings: ['cheese-foam'],
  },
  {
    id: 'p-sakura-latte',
    name: 'Сакура латте',
    slug: 'sakura-latte',
    categoryId: 'cat-seasonal',
    price: 380,
    images: [img('photo-1572286258217-215b6c060022')],
    description: 'Сезонный напиток с сиропом сакуры, молоком и лепестками съедобных цветов.',
    tags: ['new', 'signature'],
    rating: 4.9,
    reviewsCount: 42,
    calories: 230,
    caffeine: 'низкое',
    availableSizes: ['S', 'M', 'L'],
    availableToppings: ['pudding', 'jelly'],
  },
  {
    id: 'p-iced-americano',
    name: 'Айс американо',
    slug: 'iced-americano',
    categoryId: 'cat-coffee',
    price: 220,
    images: [img('photo-1551024506-0bccd828d307')],
    description: 'Чистый двойной эспрессо на льду — для тех, кто ценит вкус кофе без примесей.',
    tags: [],
    rating: 4.5,
    reviewsCount: 121,
    calories: 15,
    caffeine: 'высокое',
    availableSizes: ['S', 'M', 'L'],
    availableToppings: [],
  },
  {
    id: 'p-honey-lemon-tea',
    name: 'Медово-лимонный чай',
    slug: 'honey-lemon-tea',
    categoryId: 'cat-fruit-tea',
    price: 290,
    images: [img('photo-1499638673689-79a0b5115d87')],
    description: 'Тёплая классика: чёрный чай, свежий лимон и мёд — идеально в дождливый день.',
    tags: [],
    rating: 4.6,
    reviewsCount: 76,
    calories: 130,
    caffeine: 'низкое',
    availableSizes: ['S', 'M', 'L'],
    availableToppings: ['aloe', 'jelly'],
  },
];

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    author: 'Айгерим',
    avatarColor: 'bg-pink-300',
    rating: 5,
    date: '2026-06-18',
    text: 'Браун-шугар боба — любовь с первого глотка. Тигровые полосы прямо как в тайване!',
    productId: 'p-brown-sugar-boba',
  },
  {
    id: 'r2',
    author: 'Данияр',
    avatarColor: 'bg-mint-300',
    rating: 5,
    date: '2026-06-10',
    text: 'Флэт уайт держит планку каждый раз. Беру его каждое утро по пути на работу.',
    productId: 'p-flat-white',
  },
  {
    id: 'r3',
    author: 'Салтанат',
    avatarColor: 'bg-caramel-300',
    rating: 4,
    date: '2026-05-29',
    text: 'Клубничный фруктовый чай очень освежает, но хотелось бы больше кусочков клубники.',
    productId: 'p-strawberry-fruit-tea',
  },
  {
    id: 'r4',
    author: 'Эрлан',
    avatarColor: 'bg-pink-300',
    rating: 5,
    date: '2026-05-14',
    text: 'Приложение удобное, доставка быстрая, а сырная пенка на матче — отдельный вид искусства.',
    productId: 'p-matcha-cheese',
  },
  {
    id: 'r5',
    author: 'Бермет',
    avatarColor: 'bg-mint-300',
    rating: 5,
    date: '2026-04-30',
    text: 'Классический милк-ти — моя тихая гавань после сложного дня. Всегда одинаково вкусно.',
    productId: 'p-classic-milk-tea',
  },
];

export const ADMIN_USERS: AdminUser[] = [
  { id: 'u-1', name: 'Амина Сатыбалдиева', phone: '+996 700 123 456', orders: 14, bonusBalance: 480, joined: '2025-11-02' },
  { id: 'u-2', name: 'Айгерим Т.', phone: '+996 555 222 333', orders: 8, bonusBalance: 120, joined: '2026-01-15' },
  { id: 'u-3', name: 'Данияр С.', phone: '+996 700 987 654', orders: 21, bonusBalance: 640, joined: '2025-08-20' },
  { id: 'u-4', name: 'Бермет К.', phone: '+996 550 111 222', orders: 3, bonusBalance: 45, joined: '2026-05-30' },
  { id: 'u-5', name: 'Эрлан М.', phone: '+996 700 444 555', orders: 30, bonusBalance: 890, joined: '2025-03-11' },
];

export const MOCK_USER: User = {
  id: 'u-1',
  name: 'Амина Сатыбалдиева',
  phone: '+996 700 123 456',
  email: 'amina@example.com',
  bonusBalance: 480,
  favoriteDrinkIds: ['p-brown-sugar-boba', 'p-matcha-latte', 'p-classic-milk-tea'],
  addresses: [
    {
      id: 'a-1',
      label: 'Дом',
      street: 'ул. Чуй 123',
      apartment: 'кв. 45',
      city: 'Бишкек',
      isDefault: true,
    },
    {
      id: 'a-2',
      label: 'Работа',
      street: 'пр. Манаса 56',
      city: 'Бишкек',
    },
  ],
};

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-10482',
    date: '2026-06-28',
    status: 'completed',
    items: [
      { name: 'Браун-шугар боба', quantity: 2, price: 360, customization: 'L, 50% сахара, тапиока в карамели' },
      { name: 'Флэт уайт', quantity: 1, price: 280, customization: 'M' },
    ],
    total: 1000,
    bonusesEarned: 50,
    deliveryType: 'delivery',
  },
  {
    id: 'ORD-10361',
    date: '2026-06-15',
    status: 'completed',
    items: [{ name: 'Матча латте', quantity: 1, price: 340, customization: 'M, 30% сахара' }],
    total: 340,
    bonusesEarned: 17,
    deliveryType: 'pickup',
  },
  {
    id: 'ORD-10298',
    date: '2026-06-02',
    status: 'cancelled',
    items: [{ name: 'Клубничный фруктовый чай', quantity: 1, price: 340, customization: 'L' }],
    total: 340,
    bonusesEarned: 0,
    deliveryType: 'delivery',
  },
];

export const COUPONS: Coupon[] = [
  { id: 'c-1', code: 'SWEET10', type: 'percent', value: 10, minOrder: 500, active: true, usageCount: 342, expiresAt: '2026-08-01' },
  { id: 'c-2', code: 'WELCOME150', type: 'fixed', value: 150, minOrder: 600, active: true, usageCount: 118, expiresAt: '2026-12-31' },
  { id: 'c-3', code: 'BOBA2025', type: 'percent', value: 15, active: false, usageCount: 890, expiresAt: '2025-12-31' },
];

export const ADMIN_ORDERS: AdminOrderRow[] = [
  { id: 'ORD-10490', customer: 'Айгерим Т.', total: 1240, status: 'preparing', date: '2026-07-06', itemsCount: 3 },
  { id: 'ORD-10489', customer: 'Данияр С.', total: 560, status: 'delivering', date: '2026-07-06', itemsCount: 2 },
  { id: 'ORD-10488', customer: 'Бермет К.', total: 320, status: 'processing', date: '2026-07-06', itemsCount: 1 },
  { id: 'ORD-10487', customer: 'Эрлан М.', total: 980, status: 'completed', date: '2026-07-05', itemsCount: 3 },
  { id: 'ORD-10486', customer: 'Салтанат Ж.', total: 340, status: 'cancelled', date: '2026-07-05', itemsCount: 1 },
];

export const ANALYTICS: AnalyticsPoint[] = [
  { label: 'Пн', revenue: 42000, orders: 118 },
  { label: 'Вт', revenue: 38500, orders: 104 },
  { label: 'Ср', revenue: 51200, orders: 141 },
  { label: 'Чт', revenue: 47800, orders: 129 },
  { label: 'Пт', revenue: 63400, orders: 176 },
  { label: 'Сб', revenue: 79100, orders: 214 },
  { label: 'Вс', revenue: 71300, orders: 198 },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, count = 4): Product[] {
  return PRODUCTS.filter((p) => p.id !== product.id && p.categoryId === product.categoryId)
    .slice(0, count)
    .concat(PRODUCTS.filter((p) => p.id !== product.id && p.categoryId !== product.categoryId))
    .slice(0, count);
}

export function getCategoryById(id: string): Category | undefined {
  return CATEGORIES.find((c) => c.id === id);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
