"""customer favorites and recurring orders

Revision ID: 7c003983b74d
Revises: ecd3c7b14a5c
Create Date: 2026-07-15 10:51:08.495669
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7c003983b74d'
down_revision: Union[str, None] = 'ecd3c7b14a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Постоянный заказ (предоплаченная подписка). Уникальность customer_id —
    # «одна подписка на клиента» на уровне БД, а не только в коде.
    op.create_table('recurring_orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('product_ids', sa.JSON(), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('branch_id', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('paid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', name='uq_recurring_order_customer')
    )
    op.create_index(op.f('ix_recurring_orders_company_id'), 'recurring_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_recurring_orders_customer_id'), 'recurring_orders', ['customer_id'], unique=False)
    # server_default='[]' — иначе NOT NULL не добавить к таблице с
    # существующими клиентами (NotNullViolation). Сразу после заливки дефолт
    # снимаем: пустой список задаёт приложение (default=list), а не БД.
    op.add_column(
        'customers',
        sa.Column(
            'favorite_product_ids',
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'[]'::json"),
        ),
    )
    op.alter_column('customers', 'favorite_product_ids', server_default=None)

    # Демо-backfill: у сида избранное проставляется при создании клиента, но
    # текущая БД засеяна раньше (сид идемпотентный и повторно не идёт). Строго
    # адресно (demo-клиент) и только если пусто — на чужих БД затронет 0 строк.
    op.execute(
        """
        UPDATE customers
           SET favorite_product_ids = '["p1", "p4", "p7"]'::json
         WHERE id = 'c-sw-aigerim'
           AND favorite_product_ids::text IN ('[]', 'null')
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'favorite_product_ids')
    op.drop_index(op.f('ix_recurring_orders_customer_id'), table_name='recurring_orders')
    op.drop_index(op.f('ix_recurring_orders_company_id'), table_name='recurring_orders')
    op.drop_table('recurring_orders')
    # ### end Alembic commands ###
