"""customer profile fields

Revision ID: ecd3c7b14a5c
Revises: c23573f41ea6
Create Date: 2026-07-15 10:04:26.347521
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ecd3c7b14a5c'
down_revision: Union[str, None] = 'c23573f41ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default="" — иначе NOT NULL не добавить к таблице с существующими
    # клиентами (NotNullViolation). После заливки дефолт снимаем: значение
    # задаёт приложение, а не БД.
    op.add_column(
        'customers',
        sa.Column('first_name', sa.String(length=120), nullable=False, server_default=''),
    )
    op.add_column(
        'customers',
        sa.Column('last_name', sa.String(length=120), nullable=False, server_default=''),
    )
    op.add_column('customers', sa.Column('birth_date', sa.Date(), nullable=True))
    op.alter_column('customers', 'first_name', server_default=None)
    op.alter_column('customers', 'last_name', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'birth_date')
    op.drop_column('customers', 'last_name')
    op.drop_column('customers', 'first_name')
    # ### end Alembic commands ###
